/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        navy: '#0F1829',
        'navy-2': '#162038',
        teal: '#2EC4B6',
        'teal-2': '#1A9D91',
        gold: '#B5874F',
        'gold-2': '#D4A855',
        cream: '#F7F6F2',
        'cream-2': '#F0EDE4',
        border: '#E2DED6',
        'border-2': '#D0CBC0',
        ink: '#1A1A2E',
        'ink-2': '#374151',
        'ink-3': '#6B7280',
        'ink-4': '#9CA3AF',
        green: '#16A34A',
        amber: '#D97706',
        coral: '#E04F4F',
        violet: '#7B2D8B',
        terracotta: '#C2694F',
        leaf: '#5E8C41',
        'dim-entrepreneurial': '#2EC4B6',
        'dim-risk': '#B5874F',
        'dim-financial': '#16A34A',
        'dim-social': '#7B2D8B',
        'dim-business': '#0284C7',
        'dim-resilience': '#D97706',
        'dim-motivation': '#E04F4F',
      },
      fontFamily: {
        playfair: ['PlayfairDisplay_800ExtraBold'],
        'playfair-bold': ['PlayfairDisplay_700Bold'],
        inter: ['Inter_500Medium'],
        'inter-semi': ['Inter_600SemiBold'],
        'inter-bold': ['Inter_700Bold'],
        mono: ['JetBrainsMono_600SemiBold'],
        'mono-bold': ['JetBrainsMono_700Bold'],
        bn: ['NotoSansBengali_600SemiBold'],
        'bn-bold': ['NotoSansBengali_700Bold'],
        'bn-black': ['NotoSansBengali_800ExtraBold'],
        'bn-ui': ['HindSiliguri_600SemiBold'],
      },
    },
  },
  plugins: [],
};
